### ISSUE TITLE
[Feature Request] Support CF metadata

### ISSUE THREAD

**Issue by corporateuser** [cloudfoundry/multiapps-controller#1391]
### Description
It would be helpful to have ability to specify labels and annotations right in mta/mtad files.

### Additional information

It would be nice to have something like:
```yaml
ID: "my-mta"
_schema-version: 3.3.0
version: 1.0.0

modules:
  #A cf app which will be bound to the service
- name: my-app
  type: application
  path: "appBits.zip"
  requires:
    - name: my-service
  parameters:
    instances: 1
    labels:
     environment: staging
     type: core-modules
    annotations:
      last-change:
        author: John Doe
        date: 12-12-12
        commitId: abc4567
```
